Repository LFPy/LFPy, pull requests merged in 2020-09, with the labels that each got.

#207 Tests that currents sum to approximately zero
  LFPy/test/test_imem.py
Labels: enhancement

#206 fix morphology issue with NEURON>7.7.2
  Dockerfile
  LFPy/run_simulation.py
  LFPy/run_simulation.pyx
  LFPy/test/L23E_p23.hoc
  LFPy/test/test_morphology_import.py
  README.md
  requirements.txt
  setup.py
Labels: bugfix

#211 Set Ra and cm only if not None
  LFPy/cell.py
Labels: bugfix

#210 Formatting/future proofing
  LFPy/cell.py
  LFPy/pointprocess.py
  LFPy/run_simulation.py
  LFPy/run_simulation.pyx
  LFPy/templatecell.py
  LFPy/test/test_cell.py
  LFPy/test/test_eegmegcalc.py
  LFPy/test/test_network.py
  LFPy/test/test_networkcell.py
  LFPy/test/test_pointprocess.py
  LFPy/test/test_templatecell.py
  examples/LFPy-example-7.ipynb
  examples/example_ECoG.py
  examples/example_ECoG_4sphere.py
  requirements.txt
  setup.py
Labels: bugfix

#212 changed version to 2.1.1
  LFPy/version.py
Labels: release

#188 give default values to 4-sphere radius and sigmas. Some cleanup
  LFPy/eegmegcalc.py
  LFPy/test/test_eegmegcalc.py
Labels: enhancement

#217 converted run_simulation._run_simulation to Cell class method
  LFPy/cell.py
  LFPy/run_simulation.py
  LFPy/run_simulation.pyx
  LFPy/templatecell.py
Labels: enhancement

#221 fix pep8 violations
  LFPy/__init__.py
  LFPy/alias_method.py
  LFPy/alias_method.pyx
  LFPy/cell.py
  LFPy/inputgenerators.py
  LFPy/network.py
  LFPy/pointprocess.py
  LFPy/run_simulation.py
  LFPy/run_simulation.pyx
  LFPy/templatecell.py
  LFPy/test/common.py
  LFPy/test/test_alias_method.py
  LFPy/test/test_cell.py
  LFPy/test/test_eegmegcalc.py
  LFPy/test/test_imem.py
  LFPy/test/test_inputgenerators.py
  LFPy/test/test_misc.py
  LFPy/test/test_network.py
  LFPy/test/test_networkcell.py
  LFPy/test/test_pointprocess.py
  LFPy/test/test_recextelectrode.py
  LFPy/test/test_templatecell.py
  LFPy/test/test_tools.py
  LFPy/tools.py
  doc/conf.py
  examples/bioRxiv281717/example_parallel_network.py
  examples/bioRxiv281717/example_parallel_network_methods.py
  examples/bioRxiv281717/example_parallel_network_parameters.py
  examples/bioRxiv281717/example_parallel_network_plotting.py
  examples/bioRxiv281717/figure_2.py
  examples/bioRxiv281717/figure_4.py
  examples/bioRxiv281717/figure_5.py
  examples/bioRxiv281717/figure_6.py
  examples/bioRxiv281717/figure_7_8/example_parallel_network.py
  examples/bioRxiv281717/figure_7_8/example_parallel_network_methods.py
  examples/bioRxiv281717/figure_7_8/example_parallel_network_parameters.py
  examples/bioRxiv281717/figure_7_8/example_parallel_network_parameterspace.py
  examples/bioRxiv281717/figure_7_8/example_parallel_network_plotting.py
  examples/bioRxiv281717/figure_7_8/figure_7_8.py
  examples/example_ECoG.py
  examples/example_ECoG_4sphere.py
  examples/example_EEG.py
  examples/example_EPFL_neurons.py
  examples/example_LFPyCellTemplate.py
  examples/example_MEA.py
  examples/example_anisotropy.py
  examples/example_loadL5bPCmodelsEH.py
  examples/example_mpi.py
  examples/example_mpi_2.py
  examples/example_network/example_network.py
  examples/example_network/example_network_population.py
  examples/example_suppl.py
  examples/mazzoni_example/ref_sim.py
  examples/mazzoni_example/single_cell.py
  examples/nsg_example/nsg_example.py
  setup.py
Labels: LFPykit, bugfix, enhancement

#225 fixed examples
  examples/bioRxiv281717/example_parallel_network.py
  examples/bioRxiv281717/example_parallel_network_parameters.py
  examples/bioRxiv281717/example_parallel_network_plotting.py
  examples/bioRxiv281717/figure_2.py
  examples/bioRxiv281717/figure_4.py
  examples/bioRxiv281717/figure_5.py
  examples/bioRxiv281717/figure_6.py
  examples/bioRxiv281717/requirements.txt
Labels: LFPykit
