Repository LFPy/LFPy, pull requests merged in 2020-11, with the labels that each got.

#256 moving docker hub Dockerfile here
  Dockerfile
  README.md
Labels: enhancement

#254 Replaced static default parameters with more suited pattern. closes #253
  LFPy/cell.py
  LFPy/eegmegcalc.py
  LFPy/network.py
Labels: LFPykit, enhancement

#257 use neuron from pipy for ci
  .travis.yml
Labels: enhancement

#258 Push Python wheels to PyPI on release
  .github/workflows/pythonpublish.yml
Labels: enhancement

#255 Replaced exec calls by setattr
  LFPy/cell.py
  LFPy/network.py
  LFPy/pointprocess.py
  LFPy/test/test_network.py
  LFPy/test/test_pointprocess.py
Labels: LFPykit, enhancement

#260 Removed DeprecationWarnings
  LFPy/cell.py
  LFPy/pointprocess.py
Labels: LFPykit, enhancement

#262 Prep merge with master
  Dockerfile
Labels: LFPykit

#263 more appropriate assert patterns
  LFPy/alias_method.py
  LFPy/alias_method.pyx
  LFPy/cell.py
  LFPy/inputgenerators.py
  LFPy/network.py
  LFPy/pointprocess.py
  LFPy/run_simulation.py
  LFPy/run_simulation.pyx
Labels: LFPykit, enhancement

#265 add class LFPykit.VolumetricCurrentSourceDensity
  LFPy/__init__.py
  doc/classes.rst
Labels: LFPykit, feature

#268 bump version to 2.1.2 before 2.2rc1
  LFPy/version.py
Labels: release

#269 added some missing tests to LFPy.run_tests function
  LFPy/test/__init__.py
  LFPy/test/test_imem.py
Labels: enhancement

#272 don't build wheels
  .github/workflows/pythonpublish.yml
Labels: bugfix

#274 fixed crashing examples, bumped version
  LFPy/version.py
Labels: LFPykit, bugfix

#277 goodbye travis-ci and thanks for all the fish
  .github/workflows/python-app.yml
  .travis.yml
  .travisci/test_script.sh
  README.md
Labels: LFPykit, bugfix, enhancement
